#
# Copyright 2014-2017 Red Hat, Inc. and/or its affiliates
# and other contributors as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Get the Name of EAR
  shell: chdir="{{ hawkular_metrics_ear_dir}}" ls | grep *.ear
  register: ear_name

- name: Ensures {{ docker_dir }} dir exists
  file: path={{ docker_dir }} state=directory


- name: Get Cassandra Version
  set_fact: cassandra_version={{ ansible_env.CASSANDRA_VERSION }}
  
- name: Print Cassandra Version
  debug:
    msg: "Cassandra {{ cassandra_version }}"

- name: Get Hawkular Metrics Tag
  set_fact: hawkular_metrics_tag={{ ansible_env.HAWKULAR_METRICS_TAG }}

- name: Rename the EAR generated
  copy:
    src: "{{ hawkular_metrics_ear_dir }}/{{ear_name.stdout}}"
    dest: "{{ docker_dir }}/hawkular-metrics.ear"


- name: Generate templates
  template: >
    src="{{ item.src }}"
    dest="{{ docker_dir }}/{{ item.dest }}"
  with_items:
    - { src: "standalone.conf", dest: "standalone.conf"}
    - { src: "standalone.xml",  dest: "standalone.xml" }
    - { src: "hawkular-metrics-wrapper.sh", dest: "hawkular-metrics-wrapper.sh"}
    - { src: "config.properties", dest: "config.properties"}
    - { src: "logging.properties", dest: "logging.properties"}
    - { src: "Dockerfile", dest: "Dockerfile" }

- name: Build Image
  docker_image: >
    name="{{ hawkular_metrics_image_name }}"
    tag="{{ hawkular_metrics_tag }}"
    path="{{ docker_dir }}"
    state=build

- name: Removing Docker Directory
  file:
    path: "{{ docker_dir }}"
    state: absent

- name: Generate Docker Compose File
  template: >
    src="{{ item.src }}"
    dest="{{ inventory_dir }}/{{ item.dest }}"
  with_items:
    - { src: "docker-compose.yml", dest: "docker-compose.yml"}
